### ISSUE TITLE
🐛 We can't re run existing exporters

### ISSUE THREAD

**Issue by ShanaLMoore** [scientist-softserv/hykuup_knapsack#152]

**Comment by ShanaLMoore** [comment]
These buttons work when assets.debug is enabled in config/development.rb

**Comment by ShanaLMoore** [comment]
@kirkkwang to confirm if he's fixed this.

**Comment by jillpe** [comment]
This was fixed for UTK, this should just need to be updated - Kirk to confirm if that is true

**Comment by kirkkwang** [comment]
The buttons are fixed, however the export doesn't work for Valkyrie objects yet, here's the stack trace

<details><summary>Stack track:</summary>

```
2024-02-27T03:17:27.395Z pid=14 tid=8mle WARN: /usr/local/bundle/bundler/gems/bulkrax-6d5517d808f2/app/parsers/bulkrax/csv_parser.rb:240:in `store_files'
/usr/local/bundle/bundler/gems/bulkrax-6d5517d808f2/app/parsers/bulkrax/csv_parser.rb:230:in `block (3 levels) in write_files'
/usr/local/bundle/bundler/gems/bulkrax-6d5517d808f2/app/parsers/bulkrax/csv_parser.rb:226:in `each'
/usr/local/bundle/bundler/gems/bulkrax-6d5517d808f2/app/parsers/bulkrax/csv_parser.rb:226:in `block (2 levels) in write_files'
/usr/local/lib/ruby/3.2.0/csv.rb:1610:in `open'
/usr/local/bundle/bundler/gems/bulkrax-6d5517d808f2/app/parsers/bulkrax/csv_parser.rb:225:in `block in write_files'
/usr/local/bundle/bundler/gems/rails-d16199e50708/activesupport/lib/active_support/core_ext/array/grouping.rb:39:in `block in in_groups_of'
/usr/local/bundle/bundler/gems/rails-d16199e50708/activesupport/lib/active_support/core_ext/array/grouping.rb:39:in `each'
/usr/local/bundle/bundler/gems/rails-d16199e50708/activesupport/lib/active_support/core_ext/array/grouping.rb:39:in `each_slice'
/usr/local/bundle/bundler/gems/rails-d16199e50708/activesupport/lib/active_support/core_ext/array/grouping.rb:39:in `in_groups_of'
/usr/local/bundle/bundler/gems/bulkrax-6d5517d808f2/app/parsers/bulkrax/csv_parser.rb:222:in `write_files'
/usr/local/bundle/bundler/gems/bulkrax-6d5517d808f2/app/parsers/bulkrax/application_parser.rb:414:in `write'
/usr/local/bundle/bundler/gems/bulkrax-6d5517d808f2/app/models/bulkrax/exporter.rb:17:in `write'
/usr/local/bundle/bundler/gems/bulkrax-6d5517d808f2/app/jobs/bulkrax/exporter_job.rb:10:in `perform'
/usr/local/bundle/bundler/gems/rails-d16199e50708/activejob/lib/active_job/execution.rb:48:in `block in perform_now'
/usr/local/bundle/bundler/gems/rails-d16199e50708/activesupport/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/usr/local/bundle/gems/i18n-1.14.1/lib/i18n.rb:322:in `with_locale'
/usr/local/bundle/bundler/gems/rails-d16199e50708/activejob/lib/active_job/translation.rb:9:in `block (2 levels) in <module:Translation>'
/usr/local/bundle/bundler/gems/rails-d16199e50708/activesupport/lib/active_support/callbacks.rb:126:in `instance_exec'
/usr/local/bundle/bundler/gems/rails-d16199e50708/activesupport/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/usr/local/bundle/bundler/gems/rails-d16199e50708/activesupport/lib/active_support/core_ext/time/zones.rb:66:in `use_zone'
/usr/local/bundle/bundler/gems/rails-d16199e50708/activejob/lib/active_job/timezones.rb:9:in `block (2 levels) in <module:Timezones>'
/usr/local/bundle/bundler/gems/rails-d16199e50708/activesupport/lib/active_support/callbacks.rb:126:in `instance_exec'
/usr/local/bundle/bundler/gems/rails-d16199e50708/activesupport/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/usr/local/bundle/bundler/gems/rails-d16199e50708/activejob/lib/active_job/instrumentation.rb:21:in `block in instrument'
/usr/local/bundle/bundler/gems/rails-d16199e50708/activesupport/lib/active_support/notifications.rb:203:in `block in instrument'
/usr/local/bundle/bundler/gems/rails-d16199e50708/activesupport/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/usr/local/bundle/bundler/gems/rails-d16199e50708/activesupport/lib/active_support/notifications.rb:203:in `instrument'
/usr/local/bundle/bundler/gems/rails-d16199e50708/activejob/lib/active_job/instrumentation.rb:31:in `instrument'
/usr/local/bundle/bundler/gems/rails-d16199e50708/activejob/lib/active_job/instrumentation.rb:14:in `block (2 levels) in <module:Instrumentation>'
/usr/local/bundle/bundler/gems/rails-d16199e50708/activesupport/lib/active_support/callbacks.rb:126:in `instance_exec'
/usr/local/bundle/bundler/gems/rails-d16199e50708/activesupport/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/usr/local/bundle/bundler/gems/rails-d16199e50708/activejob/lib/active_job/logging.rb:22:in `block in tag_logger'
/usr/local/bundle/bundler/gems/rails-d16199e50708/activesupport/lib/active_support/tagged_logging.rb:99:in `block in tagged'
/usr/local/bundle/bundler/gems/rails-d16199e50708/activesupport/lib/active_support/tagged_logging.rb:37:in `tagged'
/usr/local/bundle/bundler/gems/rails-d16199e50708/activesupport/lib/active_support/tagged_logging.rb:99:in `tagged'
/usr/local/bundle/bundler/gems/rails-d16199e50708/activejob/lib/active_job/logging.rb:22:in `tag_logger'
/usr/local/bundle/bundler/gems/rails-d16199e50708/activejob/lib/active_job/logging.rb:15:in `block (2 levels) in <module:Logging>'
/usr/local/bundle/bundler/gems/rails-d16199e50708/activesupport/lib/active_support/callbacks.rb:126:in `instance_exec'
/usr/local/bundle/bundler/gems/rails-d16199e50708/activesupport/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/usr/local/bundle/bundler/gems/rails-d16199e50708/activesupport/lib/active_support/callbacks.rb:137:in `run_callbacks'
/usr/local/bundle/bundler/gems/rails-d16199e50708/activejob/lib/active_job/execution.rb:47:in `perform_now'
/app/samvera/hyrax-webapp/lib/active_job_tenant.rb:38:in `block in perform_now'
/app/samvera/hyrax-webapp/lib/active_job_tenant.rb:57:in `block in switch'
/usr/local/bundle/bundler/gems/apartment-9ad4b0ef2ee6/lib/apartment/adapters/abstract_adapter.rb:85:in `switch'
/usr/local/lib/ruby/3.2.0/forwardable.rb:240:in `switch'
/app/samvera/hyrax-webapp/lib/active_job_tenant.rb:56:in `switch'
/app/samvera/hyrax-webapp/lib/active_job_tenant.rb:37:in `perform_now'
/usr/local/bundle/bundler/gems/rails-d16199e50708/activejob/lib/active_job/execution.rb:25:in `block in execute'
/usr/local/bundle/bundler/gems/rails-d16199e50708/activesupport/lib/active_support/callbacks.rb:117:in `block in run_callbacks'
/usr/local/bundle/bundler/gems/rails-d16199e50708/activejob/lib/active_job/railtie.rb:47:in `block (4 levels) in <class:Railtie>'
/usr/local/bundle/bundler/gems/rails-d16199e50708/activesupport/lib/active_support/execution_wrapper.rb:91:in `wrap'
/usr/local/bundle/bundler/gems/rails-d16199e50708/activesupport/lib/active_support/reloader.rb:72:in `block in wrap'
/usr/local/bundle/bundler/gems/rails-d16199e50708/activesupport/lib/active_support/execution_wrapper.rb:87:in `wrap'
/usr/local/bundle/bundler/gems/rails-d16199e50708/activesupport/lib/active_support/reloader.rb:71:in `wrap'
/usr/local/bundle/bundler/gems/rails-d16199e50708/activejob/lib/active_job/railtie.rb:46:in `block (3 levels) in <class:Railtie>'
/usr/local/bundle/bundler/gems/rails-d16199e50708/activesupport/lib/active_support/callbacks.rb:126:in `instance_exec'
/usr/local/bundle/bundler/gems/rails-d16199e50708/activesupport/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
/usr/local/bundle/bundler/gems/rails-d16199e50708/activesupport/lib/active_support/callbacks.rb:137:in `run_callbacks'
/usr/local/bundle/bundler/gems/rails-d16199e50708/activejob/lib/active_job/execution.rb:23:in `execute'
/usr/local/bundle/bundler/gems/rails-d16199e50708/activejob/lib/active_job/queue_adapters/sidekiq_adapter.rb:42:in `perform'
/usr/local/bundle/gems/sidekiq-6.5.12/lib/sidekiq/processor.rb:202:in `execute_job'
/usr/local/bundle/gems/sidekiq-6.5.12/lib/sidekiq/processor.rb:170:in `block (2 levels) in process'
/usr/local/bundle/gems/sidekiq-6.5.12/lib/sidekiq/middleware/chain.rb:172:in `invoke'
/usr/local/bundle/gems/sidekiq-6.5.12/lib/sidekiq/processor.rb:169:in `block in process'
/usr/local/bundle/gems/sidekiq-6.5.12/lib/sidekiq/processor.rb:136:in `block (6 levels) in dispatch'
/usr/local/bundle/gems/sidekiq-6.5.12/lib/sidekiq/job_retry.rb:113:in `local'
/usr/local/bundle/gems/sidekiq-6.5.12/lib/sidekiq/processor.rb:135:in `block (5 levels) in dispatch'
/usr/local/bundle/gems/sidekiq-6.5.12/lib/sidekiq/rails.rb:14:in `block in call'
/usr/local/bundle/bundler/gems/rails-d16199e50708/activesupport/lib/active_support/execution_wrapper.rb:91:in `wrap'
/usr/local/bundle/bundler/gems/rails-d16199e50708/activesupport/lib/active_support/reloader.rb:72:in `block in wrap'
/usr/local/bundle/bundler/gems/rails-d16199e50708/activesupport/lib/active_support/execution_wrapper.rb:91:in `wrap'
/usr/local/bundle/bundler/gems/rails-d16199e50708/activesupport/lib/active_support/reloader.rb:71:in `wrap'
/usr/local/bundle/gems/sidekiq-6.5.12/lib/sidekiq/rails.rb:13:in `call'
/usr/local/bundle/gems/sidekiq-6.5.12/lib/sidekiq/processor.rb:131:in `block (4 levels) in dispatch'
/usr/local/bundle/gems/sidekiq-6.5.12/lib/sidekiq/processor.rb:263:in `stats'
/usr/local/bundle/gems/sidekiq-6.5.12/lib/sidekiq/processor.rb:126:in `block (3 levels) in dispatch'
/usr/local/bundle/gems/sidekiq-6.5.12/lib/sidekiq/job_logger.rb:13:in `call'
/usr/local/bundle/gems/sidekiq-6.5.12/lib/sidekiq/processor.rb:125:in `block (2 levels) in dispatch'
/usr/local/bundle/gems/sidekiq-6.5.12/lib/sidekiq/job_retry.rb:80:in `global'
/usr/local/bundle/gems/sidekiq-6.5.12/lib/sidekiq/processor.rb:124:in `block in dispatch'
/usr/local/bundle/gems/sidekiq-6.5.12/lib/sidekiq/job_logger.rb:39:in `prepare'
/usr/local/bundle/gems/sidekiq-6.5.12/lib/sidekiq/processor.rb:123:in `dispatch'
/usr/local/bundle/gems/sidekiq-6.5.12/lib/sidekiq/processor.rb:168:in `process'
/usr/local/bundle/gems/sidekiq-6.5.12/lib/sidekiq/processor.rb:78:in `process_one'
/usr/local/bundle/gems/sidekiq-6.5.12/lib/sidekiq/processor.rb:68:in `run'
/usr/local/bundle/gems/sidekiq-6.5.12/lib/sidekiq/component.rb:8:in `watchdog'
/usr/local/bundle/gems/sidekiq-6.5.12/lib/sidekiq/component.rb:17:in `block in safe_thread'
```
</details>
